language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost1.48-dev libboost-test1.48-dev libboost-program-options1.48-dev libboost-wave1.48-dev libboost-system1.48-dev libboost-thread1.48-dev libboost-filesystem1.48-dev libreadline-dev
script:
  # Test that the TOC of the description is up to date
  - tools/gen_toc -i README.md -o - -t github | diff README.md -
  # Test the code
  - tools/gcc_builtin_macros > lib/default_defines.hpp
  - tools/gcc_default_path > lib/default_sysinclude.hpp
  - mkdir bin
  - cd bin
  - cmake .. -DCMAKE_CXX_FLAGS:STRING="-std=c++0x -Wall -Werror -pedantic"
  - make
  - make test
