language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost1.48-dev libboost-test1.48-dev libboost-program-options1.48-dev libboost-wave1.48-dev libboost-system1.48-dev libboost-thread1.48-dev libboost-filesystem1.48-dev libedit-dev
script:
  - mkdir bin
  - cd bin
  - cmake .. -DCMAKE_CXX_FLAGS:STRING="-std=c++0x"
  - make
  - make test
