language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost1.48-dev libboost-test1.48-dev libboost-program-options1.48-dev libboost-wave1.48-dev libboost-system1.48-dev libboost-thread1.48-dev libboost-filesystem1.48-dev libreadline-dev
script:
  # Test the code
  - tools/gcc_builtin_macros > lib/core/default_defines.hpp
  - tools/gcc_default_path > lib/core/default_sysinclude.hpp
  - mkdir bin
  - cd bin
  - cmake .. -DCMAKE_CXX_FLAGS:STRING="-Wall -Werror -pedantic"
  - make
  - make test
